### PR TITLE
Bugged ZK Email post updates

### PR DESCRIPTION
**Pull request by Divide-By-0**
Hey @xsova113 can you fix the issues with content layer and the footnote (^1) linking?

```
 ✓ Ready in 3.7s
✘ [ERROR] TypeError: Cannot read properties of undefined (reading 'inTable')
    at Object.exitCodeText (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/mdast-util-gfm-table/lib/index.js:123:17)
    at compile (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
    at fromMarkdown (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:187:29)
    at parser (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/remark-parse/lib/index.js:18:12)
    at Function.parse (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/unified/lib/index.js:273:12)
    at executor (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/unified/lib/index.js:393:31)
    at new Promise (<anonymous>)
    at Function.process (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/unified/lib/index.js:380:14)
    at process (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:50:22)
    at onload (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/@mdx-js/esbuild/lib/index.js:151:22)
    at requestCallbacks.on-load (/Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/esbuild/lib/main.js:1434:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handleRequest (/Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/esbuild/lib/main.js:729:13) [plugin @mdx-js/esbuild]

    ../../../../projects/zkemail/website/posts/_mdx_bundler_entry_point-7b0202f9-b1dd-46cd-80a4-49df847f6d43.mdx:0:0:
      0 │ ---
        ╵ ^

Error: Found 1 problems in 5 documents.

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.
     
     • "zkemail.mdx": UnexpectedMDXError: Error: Build failed with 1 error:
     ../../../../projects/zkemail/website/posts/_mdx_bundler_entry_point-7b0202f9-b1dd-46cd-80a4-49df847f6d43.mdx:0:0: ERROR: [plugin: @mdx-js/esbuild] TypeError: Cannot read properties of undefined (reading 'inTable')
         at Object.exitCodeText (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/mdast-util-gfm-table/lib/index.js:123:17)
         at compile (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
         at fromMarkdown (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/remark-parse/node_modules/mdast-util-from-markdown/lib/index.js:187:29)
         at parser (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/remark-parse/lib/index.js:18:12)
         at Function.parse (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/unified/lib/index.js:273:12)
         at executor (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/unified/lib/index.js:393:31)
         at new Promise (<anonymous>)
         at Function.process (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/unified/lib/index.js:380:14)
         at process (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/@mdx-js/mdx/lib/util/create-format-aware-processors.js:50:22)
         at onload (file:///Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/@mdx-js/esbuild/lib/index.js:151:22)
         at requestCallbacks.on-load (/Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/esbuild/lib/main.js:1434:28)
         at processTicksAndRejections (node:internal/process/task_queues:95:5)
         at handleRequest (/Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/esbuild/lib/main.js:729:13)
     

SourceFetchDataError: {
  "_tag": "HandledFetchDataError"
  ```

### CODE REVIEW

**Comment by xsova113** [comment]
Looking into it now. I just fixed the  "_tag": "HandledFetchDataError" problem by reinstalling and downgrade remark-gfm to version 3.01. But footnotes still not displaying properly for some reason. working on it now

**Comment by xsova113** [comment]
I think it's fixed now. Just need to add a colon: right after [^1],  like so [^1]: TLS-Notary.

**Comment by Divide-By-0** [comment]
@xsova113 I still get this error:
```
Warning: React does not recognize the `arieaLabel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ariealabel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at a
    at h2
    at div
    at section
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:240:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:336:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:109:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:345:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:240:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:336:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:109:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:345:11)
    at Lazy
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:240:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:336:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:109:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:345:11)
    at Lazy
    at div
    at InnerLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:240:11)
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at NotFoundErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:336:11)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:109:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at Lazy
    at OuterLayoutRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/layout-router.js:345:11)
    at Lazy
    at m (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.js:1:419)
    at exports.ThemeProvider (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.js:1:3720)
    at ThemeProvider (webpack-internal:///(ssr)/./src/components/ThemeProviders.tsx:13:26)
    at Lazy
    at body
    at html
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:295:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:154:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:82:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:109:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:426:13)
    at Lazy
    at Lazy
    at /Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:392579
    at /Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:392579
    at ServerInsertedHTMLProvider (/Users/aayushgupta/Documents/.projects.nosync/zkemail/website/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:13:26065)
```

Also, the footnote colon doesn't seem to leave the text in between the footnote names intact.

**Comment by xsova113** [comment]
I think we can safely ignore the arieLabel warning, its just the props passed from mdx-bundler that use ariaLabel instead of aria-label.

For the footnote im not sure how much I can customize it. since its formatted by remark-gfm. though I will leave the css at the end of globals.css file, just in case if you want to customize the footnote.

**Pull request merged**
